find_path(SDL2TTF_INCLUDE_DIR "SDL_ttf.h" PATH_SUFFIXES include/SDL2 include PATHS ${SDL2TTF_ROOT_DIR})
find_library(SDL2TTF_LIBRARY_TEMP "SDL2_ttf" PATH_SUFFIXES lib/x86 PATHS ${SDL2TTF_ROOT_DIR})

if(WIN32)
	find_file(SDL2TTF_DYLIB          "SDL2_ttf.dll"      PATH_SUFFIXES lib/x86 PATHS ${SDL2TTF_ROOT_DIR} NO_DEFAULT_PATH)
	find_file(SDL2TTF_ZLIB_DYLIB     "zlib1.dll"         PATH_SUFFIXES lib/x86 PATHS ${SDL2TTF_ROOT_DIR} NO_DEFAULT_PATH)
	find_file(SDL2TTF_FREETYPE_DYLIB "libfreetype-6.dll" PATH_SUFFIXES lib/x86 PATHS ${SDL2TTF_ROOT_DIR} NO_DEFAULT_PATH)

	set(SDL2TTF_DYLIBS
		${SDL2TTF_DYLIB}
		${SDL2TTF_ZLIB_DYLIB}
		${SDL2TTF_FREETYPE_DYLIB}
	)
endif()

if(SDL2TTF_LIBRARY_TEMP)
	set(SDL2TTF_LIBRARY ${SDL2TTF_LIBRARY_TEMP} CACHE STRING "Where the SDL2TTF library can be found")
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SDL2TTF REQUIRED_VARS
	SDL2TTF_INCLUDE_DIR
	SDL2TTF_LIBRARY
)
